### ISSUE TITLE
fortls does not work properly when subroutine is renamed during module load

### ISSUE THREAD

**Issue by Koushikphy** [fortran-lang/fortls#202] opened 2022-09-28 06:41 UTC
### Discussed in https://github.com/gnikit/fortls/discussions/201

<div type='discussions-op-text'>

<sup>Originally posted by **Koushikphy** September 28, 2022</sup>
Lets say I have this sample module
```fortran
module mod

contains
    subroutine test(a)
        print*,a
    end

    subroutine tes(b)
        print*,b
    end
endmodule mod

```
And this sample program that uses the module
```fortran
program name
    use mod, tr => test

    call tr(2.0)
    call tes(3.0)
    call test(2.0)
endprogram name
```
Few observation
1. The first call `tr(2.0)` is valid and works but the `fortls` does not show this subroutine as a suggestion during write.
2. Second call `tes(3.0)` is valid and works.
3. The third call `test(2.0)` is not valid as the actual subroutine is renamed during module load. But the language server shows this as a suggestion, does not show error and when done `Ctrl+Click` it goes  to the subroutine definition in the main module.  
These problems (1 and 2) should be fixed. 

</div>

**Comment by gnikit** [comment] 2022-09-28 06:53
Please do not double post and spam the repository with duplicates issues and discussions

**Comment by Koushikphy** [comment] 2022-09-28 07:01
Then I guess, you should delete the one that does not fit here.

**Comment by gnikit** [comment] 2022-09-28 21:47
> Then I guess, you should delete the one that does not fit here.

I have deleted the duplicate discussion. In the future avoid duplicating posts, you should also be aware and abide to the [Code of Conduct](https://github.com/gnikit/fortls/blob/master/CODE_OF_CONDUCT.md) for this repo.

-----
1. Is a effectively a duplicate of https://github.com/gnikit/fortls/issues/52 (same reason although not stated explicitly in that)
2. Works as expected
3. Out of scope for the language server


As a general note, there are instructions on the fortls Issue Templates on GitHub to make the issues easier to reproduce along with documentation on the debug CLI, https://gnikit.github.io/fortls/options.html#debug-options-command-line-only. In the future please try and use those.

**Comment by gnikit** [comment] 2022-11-18 07:37
Duplicate of #52

**Closed by gnikit** 2022-11-18 07:37 UTC
